FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY OnlineCoursesAnalyzer.csproj .
RUN dotnet restore OnlineCoursesAnalyzer.csproj
COPY . .
RUN dotnet build OnlineCoursesAnalyzer.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish OnlineCoursesAnalyzer.csproj -c Release -o /app/publish

FROM nginx:alpine AS final
ENV PORT=81
COPY ./default.conf.template /default.conf.template
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
CMD ["/bin/sh" , "-c" , "envsubst < /default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]